import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const TRANSLATIONS = {
  en: {
    nav_complaint_updates: 'Complaint Updates',
    nav_latest_status_feedback: 'Latest status feedback from leader team',
    nav_no_notifications: 'No new notifications',
    nav_unread: 'Unread',
    nav_notifications_title: 'Complaint notifications',
    nav_logout: 'Logout',
    nav_help_center: 'Help Center',
    nav_light: 'Light',
    nav_dark: 'Dark',
    nav_theme_light: 'Switch to light mode',
    nav_theme_dark: 'Switch to dark mode',
    lang_en: 'EN',
    lang_hi: 'HI',

    side_register_complaint: 'Register Complaint',
    side_my_complaints: 'My Complaints',
    side_dashboard: 'Dashboard',
    side_manage_complaints: 'Manage Complaints',
    side_social_media: 'Social Media',
    side_communications: 'Communications',
    side_public_portal: 'Public Portal',
    side_my_profile: 'My Profile',
    side_help_center: 'Help Center',
    side_about_developer: 'About Developer',
    side_platform_tagline: 'AI-Powered Governance Intelligence Platform',

    register_citizen_desk: 'Citizen Desk',
    register_title: 'Register Complaint',
    register_subtitle: 'Submit issues through text, voice, or image evidence. Complaints are triaged and prioritized automatically for governance teams.',
    register_smart_intake: 'Smart Intake',
    register_smart_intake_desc: 'Multimodal complaint capture',
    register_voice_ai: 'Voice AI',
    register_voice_ai_desc: 'Whisper transcription support',
    register_geo_evidence: 'Geo Evidence',
    register_geo_evidence_desc: 'Location-aware verification flow',
    register_live_tracking: 'Live Tracking',
    register_live_tracking_desc: 'Status alerts on every update',
    register_text: 'Text',
    register_voice: 'Voice',
    register_image: 'Image',
    register_ward: 'Ward',
    register_problem_category: 'Problem category',
    register_auto_detect: 'Auto-detect',
    register_language: 'Language',
    register_phone_optional: 'Phone (optional)',
    register_complaint_details: 'Complaint details',
    register_complaint_placeholder: 'Describe the issue, location, and urgency...',
    register_start_mic: 'Start Mic',
    register_stop_mic: 'Stop Mic',
    register_mic_hint: 'Mic stops automatically after silence.',
    register_voice_file: 'Voice file',
    register_voice_upload_hint: 'Upload a voice note (mp3, wav, m4a).',
    register_image_evidence: 'Image evidence',
    register_image_upload_hint: 'Upload a clear photo of the issue location.',
    register_geo_title: 'Geo-Tagged Work Verification',
    register_geo_default: 'Upload an image with GPS metadata or use current location.',
    register_geo_use_current: 'Use current location',
    register_submit: 'Submit Complaint',
    register_submitting: 'Submitting complaint...',
    register_latest_status: 'Latest Complaint Status',
    register_recent_statuses: 'Recent complaint statuses for your mobile number.',
    register_loading_latest: 'Loading latest statuses...',
    register_no_recent: 'No recent complaints found. Submit one to track status here.',
    register_transcription_preview: 'Whisper transcription preview',

    profile_title: 'My Profile',
    profile_edit_account: 'Edit Account Details',
    profile_change_details: 'Change Details',
    profile_cancel: 'Cancel',
    profile_save_changes: 'Save Changes',
    profile_saving: 'Saving...',

    status_open: 'Open',
    status_under_review: 'Under Review',
    status_assigned: 'Assigned',
    status_in_progress: 'In Progress',
    status_verification_pending: 'Verification Pending',
    status_resolved: 'Resolved',
    status_verified: 'Verified',
    status_closed: 'Closed',

    login_welcome_back: 'Welcome back',
    login_create_account_title: 'Create your account',
    login_reset_password_title: 'Reset your password',
    login_subtitle_signin: 'Sign in to monitor complaints, trust signals, and response workflows.',
    login_subtitle_register: 'Set up your account to start managing governance operations.',
    login_subtitle_forgot: 'Enter your email and set a fresh password to regain access.',
    login_create_account: 'Create Account',
    login_reset_password: 'Reset Password',
    login_sign_in: 'Sign In',
    login_trusted_hub: 'Trusted civic operations hub',
    login_empowering_citizens: 'Empowering citizens',
    login_command_center: 'Operational command center for grievance intake, triage, and transparent follow-up.',
    login_citizen_first: 'Citizen First Governance',
    login_citizen_first_desc: 'Faster grievance redressal, transparent status tracking, and trusted civic delivery for every ward.',
    login_back_to_signin: 'Back to sign in',
    login_full_name: 'Full name',
    login_your_full_name: 'Your full name',
    login_account_type: 'Account type',
    login_role_citizen: 'Citizen',
    login_role_leader: 'Leader',
    login_role_worker: 'Worker',
    login_email: 'Email address',
    login_email_placeholder: 'name@domain.gov',
    login_new_password: 'New password',
    login_password: 'Password',
    login_forgot_password: 'Forgot password?',
    login_password_placeholder: 'At least 8 characters',
    login_hide_password: 'Hide password',
    login_show_password: 'Show password',
    login_confirm_new_password: 'Confirm new password',
    login_confirm_password_placeholder: 'Re-enter your new password',
    login_please_wait: 'Please wait...',
    login_secure_access: 'Secure access for authorized civic operations teams.',
    login_err_new_password_length: 'New password must be at least 8 characters long.',
    login_err_password_mismatch: 'Passwords do not match.',
    login_success_password_updated: 'Password updated. You can now sign in with your new password.',
    login_success_account_created: 'Account created successfully. Signing you in...',
    login_success_welcome_prefix: 'Welcome back',
    login_success_redirecting: 'Redirecting to your dashboard...',
    login_user_fallback: 'User',
    login_welcome_badge: 'Signed In',
    login_live_monitoring: 'Live civic monitoring enabled',
    login_chip_secure: 'Secure Login',
    login_chip_fast: 'Fast Access',
    login_chip_role: 'Role Aware',
    login_err_registration_failed: 'Registration failed. Please try again.',
    login_err_reset_failed: 'Password reset failed. Please try again.',
    login_err_login_failed: 'Login failed. Please try again.',

    dashboard_console: 'Jansewa Leader Console',
    dashboard_title: 'Leader Dashboard',
    dashboard_subtitle: 'Real-time civic intelligence for city operations',
    dashboard_live_refresh: 'Live Refresh: 20s',
    dashboard_last_update: 'Last update',
    dashboard_failed_load: 'Failed to load dashboard data',
    dashboard_loading: 'Loading dashboard...',
    common_na: 'N/A',

    stats_total_complaints: 'Total Complaints',
    stats_pending: 'Pending',
    stats_in_progress: 'In Progress',
    stats_resolved: 'Resolved',
    stats_critical: 'Critical',
    stats_avg_resolution: 'Avg Resolution (hrs)',

    queue_empty: 'No complaints in queue',
    queue_title: 'Priority Queue',
    queue_subtitle: 'Top complaints ranked by AI priority score',
    queue_ward_na: 'Ward N/A',
    queue_category_na: 'Category N/A',
    queue_score: 'Score',
    queue_complaint_fallback: 'Complaint',

    alerts_none: 'No active alerts',
    alerts_title: 'Active Alerts',
    alerts_subtitle: 'Real-time alerts from social media and AI',
    alerts_social_detected: 'Social alert detected',
    alerts_sentiment: 'Sentiment',
    alerts_virality: 'Virality',

    heatmap_title: 'Ward Heat Map',
    heatmap_subtitle: 'Complaint density by geographic area',

    sentiment_title: 'Sentiment Trend',
    sentiment_subtitle: 'Public sentiment over time from social media',
    sentiment_positive: 'Positive',
    sentiment_negative: 'Negative',
    sentiment_neutral: 'Neutral',

    manage_title: 'Manage Complaints',
    manage_subtitle: 'Review all complaints and update lifecycle status from one place.',
    manage_filter_status: 'Filter by status',
    manage_all_statuses: 'All statuses',
    manage_failed_load: 'Failed to load complaints.',
    manage_status_update_failed: 'Status update failed.',
    manage_col_complaint: 'Complaint',
    manage_col_ward: 'Ward',
    manage_col_input: 'Input',
    manage_col_priority: 'Priority',
    manage_col_current_status: 'Current Status',
    manage_col_change_status: 'Change Status',
    manage_loading: 'Loading complaints...',
    manage_no_complaints: 'No complaints found.',
    manage_no_text: 'No text summary available',
    manage_open_details: 'Open details',

    complaint_loading: 'Loading complaint...',
    complaint_not_found: 'Complaint not found',
    complaint_back_dashboard: 'Back to Dashboard',
    complaint_dashboard: 'Dashboard',
    complaint_details_title: 'Complaint Details',
    complaint_filed_on: 'Filed on',
    complaint_no_text_details: 'No text details provided.',
    complaint_meta_ward: 'Ward',
    complaint_meta_category: 'Category',
    complaint_meta_priority_score: 'Priority Score',
    complaint_meta_sentiment: 'Sentiment',
    complaint_meta_source: 'Source',
    complaint_meta_created: 'Created',
    complaint_meta_assigned_to: 'Assigned To',
    complaint_meta_ai_duplicate: 'AI Duplicate',
    complaint_meta_detected_location: 'Detected Location',
    complaint_yes: 'Yes',
    complaint_no: 'No',
    complaint_ai_summary: 'AI Summary',
    complaint_attached_image: 'Attached Image',
    complaint_open_full_image: 'Open full image',
    complaint_verification_title: '4-Layer Verification',
    complaint_verify_gps: 'GPS Match',
    complaint_verify_timestamp: 'Timestamp',
    complaint_verify_visual: 'Visual Check',
    complaint_verify_tamper: 'Tamper Detect',
    complaint_overall_score: 'Overall Score',
    complaint_verified: 'Verified',
    complaint_not_verified: 'Not Verified',
    complaint_update_status: 'Update Status',
    complaint_status_updated: 'Complaint status updated successfully.',
    complaint_status_update_failed: 'Status update failed.',
    complaint_select_status: 'Select status...',
    complaint_notes_optional: 'Notes (optional)',
    complaint_updating: 'Updating...',
    complaint_update: 'Update',
    complaint_pass: 'Pass',
    complaint_fail: 'Fail',
    complaint_score: 'Score',

    verification_loading: 'Loading verification...',
    verification_title: '4-Layer Verification',
    verification_result: 'Verification Result',
    verification_submit_title: 'Submit Verification Evidence',
    verification_photo_evidence: 'Photo evidence',
    verification_latitude: 'Latitude',
    verification_longitude: 'Longitude',
    verification_auto_detected: 'Auto-detected',
    verification_notes: 'Notes',
    verification_notes_placeholder: 'Any additional observations...',
    verification_submitting: 'Submitting...',
    verification_submit: 'Submit Verification',
    verification_submission_failed: 'Verification submission failed',
    verification_overall: 'Overall',
    verification_visual_change: 'Visual Change',
    verification_tamper_detection: 'Tamper Detection',

    social_loading: 'Loading social media insights...',
    social_title: 'Social Media Intelligence',
    social_subtitle: 'Real-time monitoring of public discourse',
    social_scan_now: 'Scan Now',
    social_scanning: 'Scanning...',
    social_active_alerts: 'Active Alerts',
    social_social_feed: 'Social Feed',
    social_no_posts: 'No posts found. Click "Scan Now" to fetch.',
    social_ward: 'Ward',
    social_anonymous: 'anonymous',

    comms_loading: 'Loading communications...',
    comms_title: 'AI Communications',
    comms_subtitle: 'Generate, approve, and publish governance communications',
    comms_close: 'Close',
    comms_generate_new: '+ Generate New',
    comms_generate_title: 'Generate Communication',
    comms_complaint_id_optional: 'Complaint ID (optional)',
    comms_type: 'Type',
    comms_format: 'Format',
    comms_language: 'Language',
    comms_english: 'English',
    comms_hindi: 'Hindi',
    comms_bilingual: 'Bilingual',
    comms_generating: 'Generating with AI...',
    comms_generate: 'Generate',
    comms_generated_content: 'Generated Content',
    comms_hindi_version: 'Hindi Version',
    comms_all: 'All Communications',
    comms_none: 'No communications yet',
    comms_approve: 'Approve',
    comms_publish: 'Publish',
    comms_generation_failed: 'Generation failed',

    public_title: 'Jansewa AI Public Portal',
    public_subtitle: 'Transparent governance for every citizen',
    public_select_ward: 'Select Ward:',
    public_close: 'Close',
    public_report_issue: 'Report Issue',
    public_report_grievance: 'Report a Grievance',
    public_brief_title: 'Brief title',
    public_describe_issue: 'Describe the issue in detail...',
    public_phone_optional: 'Phone (optional)',
    public_submitting: 'Submitting...',
    public_submit: 'Submit',
    public_submitted_success: 'Your complaint has been submitted and will be processed by AI.',
    public_loading_ward: 'Loading ward data...',
    public_ward_scorecard: 'Ward Scorecard',
    public_total_complaints: 'Total Complaints',
    public_resolved: 'Resolved',
    public_pending: 'Pending',
    public_avg_resolution: 'Avg Resolution',
    public_hours: 'hrs',
    public_trust_score: 'Trust Score',
    public_responsiveness: 'Responsiveness',
    public_resolution: 'Resolution',
    public_transparency: 'Transparency',
    public_citizen_satisfaction: 'Citizen Satisfaction',
    public_recent_actions: 'Recent Actions',
    public_no_recent_actions: 'No recent actions for this ward',
    public_recently_updated: 'Recently updated',
    public_ward_map: 'Ward Map',
    public_footer: 'Empowering transparent local governance',
    public_submission_failed: 'Submission failed',

    my_title: 'My Complaints',
    my_subtitle: 'Track complete complaint history and the latest progress timeline.',
    my_total: 'Total',
    my_open: 'Open',
    my_in_progress: 'In Progress',
    my_resolved: 'Resolved',
    my_add_mobile_hint: 'Add your mobile number in My Profile to view complaint history.',
    my_search: 'Search',
    my_search_placeholder: 'Search complaint text',
    my_status: 'Status',
    my_all_statuses: 'All statuses',
    my_refresh: 'Refresh',
    my_latest_notifications: 'Latest Notifications',
    my_notifications_subtitle: 'Leader feedback and status changes for your complaints.',
    my_recent: 'recent',
    my_loading_notifications: 'Loading notifications...',
    my_no_notifications: 'No notifications yet. Updates will appear when leaders change status.',
    my_complaint_update: 'Complaint update',
    my_open_complaint: 'Open complaint',
    my_loading_complaints: 'Loading complaints...',
    my_no_filtered: 'No complaints found for the selected filters.',
    my_complaint: 'Complaint',
    my_view_details: 'View details',
    my_latest_feedback: 'Latest Leader Feedback',
    my_no_leader_note: 'No leader note yet. You will get notified when status changes.',
    my_progress_timeline: 'Progress Timeline',

    help_title: 'Need Help?',
    help_subtitle: 'Call Jansewa helpline for immediate support',
    help_call_now: 'Call 1800-123-456',
    help_center_tag: 'Support Hub',
    help_center_title: 'Jansewa Help Center',
    help_center_subtitle: 'Find role-based guidance for citizens, leaders, officers, and engineers. Powered by Jansewa internal knowledge base.',
    help_center_search_placeholder: 'Search: assignment, verification, notifications, tracking...',
    help_center_search: 'Search Help',
    help_center_reset: 'Reset',
    help_center_all_topics: 'All Topics',
    help_center_channel_phone: 'Helpline',
    help_center_channel_phone_desc: 'Immediate support for critical civic issues',
    help_center_channel_email: 'Support Email',
    help_center_channel_email_desc: 'Operational, onboarding, and feature guidance',
    help_center_channel_sla: 'Typical SLA',
    help_center_channel_sla_desc: 'Depends on severity and department workload',
    help_center_guides: 'Guides & SOPs',
    help_center_results: 'results',
    help_center_loading: 'Loading help guides...',
    help_center_no_results: 'No matching guide found. Try a broader keyword.',
    help_load_failed: 'Unable to load help center right now.',

    citizen_dash_header_tag: 'Citizen Analytics',
    citizen_dash_title: 'Citizen Real-Time Dashboard',
    citizen_dash_subtitle: 'Live tracking of your complaints, response velocity, and latest leadership updates.',
    citizen_dash_last_updated: 'Last updated',
    citizen_dash_load_failed: 'Could not load your dashboard analytics right now.',
    citizen_dash_total: 'Total',
    citizen_dash_active: 'Active',
    citizen_dash_resolved: 'Resolved',
    citizen_dash_critical: 'Critical',
    citizen_dash_recent7: 'Last 7 Days',
    citizen_dash_rate: 'Resolution %',
    citizen_dash_recent_complaints: 'Recent Complaints',
    citizen_dash_loading: 'Loading live analytics...',
    citizen_dash_no_complaints: 'No complaints yet. Start by registering one.',
    citizen_dash_live_updates: 'Live Updates',
    citizen_dash_no_updates: 'No updates yet. Status changes will appear here.',
  },
  hi: {
    nav_complaint_updates: 'शिकायत अपडेट',
    nav_latest_status_feedback: 'लीडर टीम से नवीनतम स्थिति प्रतिक्रिया',
    nav_no_notifications: 'कोई नई सूचना नहीं',
    nav_unread: 'अपठित',
    nav_notifications_title: 'शिकायत सूचनाएं',
    nav_logout: 'लॉगआउट',
    nav_help_center: 'हेल्प सेंटर',
    nav_light: 'लाइट',
    nav_dark: 'डार्क',
    nav_theme_light: 'लाइट मोड पर स्विच करें',
    nav_theme_dark: 'डार्क मोड पर स्विच करें',
    lang_en: 'EN',
    lang_hi: 'HI',

    side_register_complaint: 'शिकायत दर्ज करें',
    side_my_complaints: 'मेरी शिकायतें',
    side_dashboard: 'डैशबोर्ड',
    side_manage_complaints: 'शिकायत प्रबंधन',
    side_social_media: 'सोशल मीडिया',
    side_communications: 'संचार',
    side_public_portal: 'पब्लिक पोर्टल',
    side_my_profile: 'मेरी प्रोफाइल',
    side_help_center: 'हेल्प सेंटर',
    side_about_developer: 'डेवलपर के बारे में',
    side_platform_tagline: 'एआई आधारित शासन इंटेलिजेंस प्लेटफॉर्म',

    register_citizen_desk: 'नागरिक डेस्क',
    register_title: 'शिकायत पंजीकरण',
    register_subtitle: 'टेक्स्ट, आवाज या छवि के माध्यम से समस्या भेजें। शिकायतों का प्राथमिकता-आधारित विश्लेषण स्वतः किया जाता है।',
    register_smart_intake: 'स्मार्ट इनटेक',
    register_smart_intake_desc: 'मल्टीमोड शिकायत संग्रह',
    register_voice_ai: 'वॉइस एआई',
    register_voice_ai_desc: 'Whisper ट्रांसक्रिप्शन सपोर्ट',
    register_geo_evidence: 'जियो साक्ष्य',
    register_geo_evidence_desc: 'लोकेशन आधारित सत्यापन प्रवाह',
    register_live_tracking: 'लाइव ट्रैकिंग',
    register_live_tracking_desc: 'हर अपडेट पर स्थिति सूचना',
    register_text: 'टेक्स्ट',
    register_voice: 'आवाज',
    register_image: 'छवि',
    register_ward: 'वार्ड',
    register_problem_category: 'समस्या श्रेणी',
    register_auto_detect: 'स्वतः पहचान',
    register_language: 'भाषा',
    register_phone_optional: 'फोन (वैकल्पिक)',
    register_complaint_details: 'शिकायत विवरण',
    register_complaint_placeholder: 'समस्या, स्थान और तात्कालिकता बताएं...',
    register_start_mic: 'माइक शुरू करें',
    register_stop_mic: 'माइक बंद करें',
    register_mic_hint: 'कुछ सेकंड की चुप्पी पर माइक अपने आप बंद होगा।',
    register_voice_file: 'वॉइस फ़ाइल',
    register_voice_upload_hint: 'वॉइस नोट अपलोड करें (mp3, wav, m4a)।',
    register_image_evidence: 'छवि साक्ष्य',
    register_image_upload_hint: 'समस्या स्थान की स्पष्ट फोटो अपलोड करें।',
    register_geo_title: 'जियो-टैग्ड कार्य सत्यापन',
    register_geo_default: 'GPS मेटाडेटा वाली छवि अपलोड करें या वर्तमान स्थान चुनें।',
    register_geo_use_current: 'वर्तमान स्थान उपयोग करें',
    register_submit: 'शिकायत सबमिट करें',
    register_submitting: 'शिकायत भेजी जा रही है...',
    register_latest_status: 'नवीनतम शिकायत स्थिति',
    register_recent_statuses: 'आपके मोबाइल नंबर की हाल की शिकायत स्थितियां।',
    register_loading_latest: 'स्थिति लोड हो रही है...',
    register_no_recent: 'कोई हाल की शिकायत नहीं मिली। ट्रैक करने के लिए नई शिकायत दर्ज करें।',
    register_transcription_preview: 'Whisper ट्रांसक्रिप्शन पूर्वावलोकन',

    profile_title: 'मेरी प्रोफाइल',
    profile_edit_account: 'खाता विवरण संपादित करें',
    profile_change_details: 'विवरण बदलें',
    profile_cancel: 'रद्द करें',
    profile_save_changes: 'परिवर्तन सहेजें',
    profile_saving: 'सहेजा जा रहा है...',

    status_open: 'खुला',
    status_under_review: 'समीक्षा में',
    status_assigned: 'आवंटित',
    status_in_progress: 'कार्य प्रगति पर',
    status_verification_pending: 'सत्यापन लंबित',
    status_resolved: 'समाधान हुआ',
    status_verified: 'सत्यापित',
    status_closed: 'बंद',

    login_welcome_back: 'फिर से स्वागत है',
    login_create_account_title: 'अपना खाता बनाएं',
    login_reset_password_title: 'पासवर्ड रीसेट करें',
    login_subtitle_signin: 'शिकायतें, ट्रस्ट संकेत और प्रतिक्रिया वर्कफ़्लो देखने के लिए साइन इन करें।',
    login_subtitle_register: 'शासन संचालन शुरू करने के लिए अपना खाता सेट करें।',
    login_subtitle_forgot: 'अपना ईमेल दर्ज करें और नई पासवर्ड सेट करें।',
    login_create_account: 'खाता बनाएं',
    login_reset_password: 'पासवर्ड रीसेट',
    login_sign_in: 'साइन इन',
    login_trusted_hub: 'विश्वसनीय नागरिक संचालन केंद्र',
    login_empowering_citizens: 'नागरिकों को सशक्त बनाना',
    login_command_center: 'शिकायत प्राप्ति, प्राथमिकता निर्धारण और पारदर्शी फॉलो-अप के लिए ऑपरेशनल कमांड सेंटर।',
    login_citizen_first: 'नागरिक प्रथम शासन',
    login_citizen_first_desc: 'तेज़ शिकायत निवारण, पारदर्शी स्थिति ट्रैकिंग और हर वार्ड के लिए भरोसेमंद सेवा।',
    login_back_to_signin: 'साइन इन पर वापस जाएं',
    login_full_name: 'पूरा नाम',
    login_your_full_name: 'आपका पूरा नाम',
    login_account_type: 'खाता प्रकार',
    login_role_citizen: 'नागरिक',
    login_role_leader: 'लीडर',
    login_role_worker: 'कर्मी',
    login_email: 'ईमेल पता',
    login_email_placeholder: 'name@domain.gov',
    login_new_password: 'नई पासवर्ड',
    login_password: 'पासवर्ड',
    login_forgot_password: 'पासवर्ड भूल गए?',
    login_password_placeholder: 'कम से कम 8 अक्षर',
    login_hide_password: 'पासवर्ड छिपाएं',
    login_show_password: 'पासवर्ड दिखाएं',
    login_confirm_new_password: 'नई पासवर्ड की पुष्टि करें',
    login_confirm_password_placeholder: 'नई पासवर्ड फिर से दर्ज करें',
    login_please_wait: 'कृपया प्रतीक्षा करें...',
    login_secure_access: 'अधिकृत नागरिक संचालन टीमों के लिए सुरक्षित पहुंच।',
    login_err_new_password_length: 'नई पासवर्ड कम से कम 8 अक्षरों की होनी चाहिए।',
    login_err_password_mismatch: 'पासवर्ड मेल नहीं खाते।',
    login_success_password_updated: 'पासवर्ड अपडेट हो गया। अब आप नई पासवर्ड से साइन इन कर सकते हैं।',
    login_success_account_created: 'खाता सफलतापूर्वक बन गया। आपको साइन इन किया जा रहा है...',
    login_success_welcome_prefix: 'फिर से स्वागत है',
    login_success_redirecting: 'आपके डैशबोर्ड पर भेजा जा रहा है...',
    login_user_fallback: 'उपयोगकर्ता',
    login_welcome_badge: 'साइन इन हो गया',
    login_live_monitoring: 'लाइव नागरिक मॉनिटरिंग सक्रिय है',
    login_chip_secure: 'सुरक्षित लॉगिन',
    login_chip_fast: 'तेज़ प्रवेश',
    login_chip_role: 'भूमिका आधारित',
    login_err_registration_failed: 'पंजीकरण विफल। कृपया पुनः प्रयास करें।',
    login_err_reset_failed: 'पासवर्ड रीसेट विफल। कृपया पुनः प्रयास करें।',
    login_err_login_failed: 'लॉगिन विफल। कृपया पुनः प्रयास करें।',

    dashboard_console: 'जनसेवा लीडर कंसोल',
    dashboard_title: 'लीडर डैशबोर्ड',
    dashboard_subtitle: 'भारतीय तिरंगा थीम के साथ रीयल-टाइम नागरिक इंटेलिजेंस',
    dashboard_live_refresh: 'लाइव रिफ्रेश: 20 सेकंड',
    dashboard_last_update: 'अंतिम अपडेट',
    dashboard_failed_load: 'डैशबोर्ड डेटा लोड नहीं हुआ',
    dashboard_loading: 'डैशबोर्ड लोड हो रहा है...',
    common_na: 'उपलब्ध नहीं',

    stats_total_complaints: 'कुल शिकायतें',
    stats_pending: 'लंबित',
    stats_in_progress: 'प्रगति पर',
    stats_resolved: 'समाधान हुआ',
    stats_critical: 'गंभीर',
    stats_avg_resolution: 'औसत समाधान (घंटे)',

    queue_empty: 'कतार में कोई शिकायत नहीं',
    queue_title: 'प्राथमिकता कतार',
    queue_subtitle: 'एआई प्राथमिकता स्कोर के आधार पर शीर्ष शिकायतें',
    queue_ward_na: 'वार्ड उपलब्ध नहीं',
    queue_category_na: 'श्रेणी उपलब्ध नहीं',
    queue_score: 'स्कोर',
    queue_complaint_fallback: 'शिकायत',

    alerts_none: 'कोई सक्रिय अलर्ट नहीं',
    alerts_title: 'सक्रिय अलर्ट',
    alerts_subtitle: 'सोशल मीडिया और एआई से रीयल-टाइम अलर्ट',
    alerts_social_detected: 'सोशल अलर्ट मिला',
    alerts_sentiment: 'भावना',
    alerts_virality: 'वायरैलिटी',

    heatmap_title: 'वार्ड हीट मैप',
    heatmap_subtitle: 'भौगोलिक क्षेत्र के अनुसार शिकायत घनत्व',

    sentiment_title: 'भावना रुझान',
    sentiment_subtitle: 'समय के साथ सोशल मीडिया से सार्वजनिक भावना',
    sentiment_positive: 'सकारात्मक',
    sentiment_negative: 'नकारात्मक',
    sentiment_neutral: 'तटस्थ',

    manage_title: 'शिकायत प्रबंधन',
    manage_subtitle: 'एक जगह से शिकायतों की समीक्षा करें और स्थिति अपडेट करें।',
    manage_filter_status: 'स्थिति के अनुसार फ़िल्टर',
    manage_all_statuses: 'सभी स्थितियां',
    manage_failed_load: 'शिकायतें लोड नहीं हुईं।',
    manage_status_update_failed: 'स्थिति अपडेट विफल।',
    manage_col_complaint: 'शिकायत',
    manage_col_ward: 'वार्ड',
    manage_col_input: 'इनपुट',
    manage_col_priority: 'प्राथमिकता',
    manage_col_current_status: 'वर्तमान स्थिति',
    manage_col_change_status: 'स्थिति बदलें',
    manage_loading: 'शिकायतें लोड हो रही हैं...',
    manage_no_complaints: 'कोई शिकायत नहीं मिली।',
    manage_no_text: 'टेक्स्ट सार उपलब्ध नहीं',
    manage_open_details: 'विवरण खोलें',

    complaint_loading: 'शिकायत लोड हो रही है...',
    complaint_not_found: 'शिकायत नहीं मिली',
    complaint_back_dashboard: 'डैशबोर्ड पर वापस',
    complaint_dashboard: 'डैशबोर्ड',
    complaint_details_title: 'शिकायत विवरण',
    complaint_filed_on: 'दर्ज किया गया',
    complaint_no_text_details: 'कोई टेक्स्ट विवरण उपलब्ध नहीं।',
    complaint_meta_ward: 'वार्ड',
    complaint_meta_category: 'श्रेणी',
    complaint_meta_priority_score: 'प्राथमिकता स्कोर',
    complaint_meta_sentiment: 'भावना',
    complaint_meta_source: 'स्रोत',
    complaint_meta_created: 'निर्मित',
    complaint_meta_assigned_to: 'आवंटित',
    complaint_meta_ai_duplicate: 'एआई डुप्लिकेट',
    complaint_meta_detected_location: 'पहचाना गया स्थान',
    complaint_yes: 'हाँ',
    complaint_no: 'नहीं',
    complaint_ai_summary: 'एआई सारांश',
    complaint_attached_image: 'संलग्न छवि',
    complaint_open_full_image: 'पूरी छवि खोलें',
    complaint_verification_title: '4-स्तरीय सत्यापन',
    complaint_verify_gps: 'GPS मिलान',
    complaint_verify_timestamp: 'टाइमस्टैम्प',
    complaint_verify_visual: 'दृश्य जांच',
    complaint_verify_tamper: 'छेड़छाड़ जांच',
    complaint_overall_score: 'कुल स्कोर',
    complaint_verified: 'सत्यापित',
    complaint_not_verified: 'असत्यापित',
    complaint_update_status: 'स्थिति अपडेट करें',
    complaint_status_updated: 'शिकायत स्थिति सफलतापूर्वक अपडेट हुई।',
    complaint_status_update_failed: 'स्थिति अपडेट विफल।',
    complaint_select_status: 'स्थिति चुनें...',
    complaint_notes_optional: 'नोट्स (वैकल्पिक)',
    complaint_updating: 'अपडेट हो रहा है...',
    complaint_update: 'अपडेट',
    complaint_pass: 'पास',
    complaint_fail: 'फेल',
    complaint_score: 'स्कोर',

    verification_loading: 'सत्यापन लोड हो रहा है...',
    verification_title: '4-स्तरीय सत्यापन',
    verification_result: 'सत्यापन परिणाम',
    verification_submit_title: 'सत्यापन साक्ष्य जमा करें',
    verification_photo_evidence: 'फोटो साक्ष्य',
    verification_latitude: 'अक्षांश',
    verification_longitude: 'देशांतर',
    verification_auto_detected: 'स्वतः पहचाना गया',
    verification_notes: 'नोट्स',
    verification_notes_placeholder: 'कोई अतिरिक्त अवलोकन...',
    verification_submitting: 'जमा हो रहा है...',
    verification_submit: 'सत्यापन जमा करें',
    verification_submission_failed: 'सत्यापन जमा विफल',
    verification_overall: 'कुल',
    verification_visual_change: 'दृश्य परिवर्तन',
    verification_tamper_detection: 'छेड़छाड़ पहचान',

    social_loading: 'सोशल मीडिया इनसाइट्स लोड हो रहे हैं...',
    social_title: 'सोशल मीडिया इंटेलिजेंस',
    social_subtitle: 'सार्वजनिक चर्चाओं की रीयल-टाइम निगरानी',
    social_scan_now: 'अभी स्कैन करें',
    social_scanning: 'स्कैन हो रहा है...',
    social_active_alerts: 'सक्रिय अलर्ट',
    social_social_feed: 'सोशल फीड',
    social_no_posts: 'कोई पोस्ट नहीं मिली। लाने के लिए "अभी स्कैन करें" क्लिक करें।',
    social_ward: 'वार्ड',
    social_anonymous: 'अनाम',

    comms_loading: 'संचार लोड हो रहा है...',
    comms_title: 'एआई संचार',
    comms_subtitle: 'शासन संचार बनाएं, अनुमोदित करें और प्रकाशित करें',
    comms_close: 'बंद करें',
    comms_generate_new: '+ नया बनाएं',
    comms_generate_title: 'संचार बनाएं',
    comms_complaint_id_optional: 'शिकायत आईडी (वैकल्पिक)',
    comms_type: 'प्रकार',
    comms_format: 'फॉर्मेट',
    comms_language: 'भाषा',
    comms_english: 'अंग्रेज़ी',
    comms_hindi: 'हिंदी',
    comms_bilingual: 'द्विभाषी',
    comms_generating: 'एआई से बनाया जा रहा है...',
    comms_generate: 'बनाएं',
    comms_generated_content: 'बनाई गई सामग्री',
    comms_hindi_version: 'हिंदी संस्करण',
    comms_all: 'सभी संचार',
    comms_none: 'अभी कोई संचार नहीं',
    comms_approve: 'अनुमोदित करें',
    comms_publish: 'प्रकाशित करें',
    comms_generation_failed: 'निर्माण विफल',

    public_title: 'जनसेवा एआई पब्लिक पोर्टल',
    public_subtitle: 'हर नागरिक के लिए पारदर्शी शासन',
    public_select_ward: 'वार्ड चुनें:',
    public_close: 'बंद करें',
    public_report_issue: 'समस्या दर्ज करें',
    public_report_grievance: 'शिकायत दर्ज करें',
    public_brief_title: 'संक्षिप्त शीर्षक',
    public_describe_issue: 'समस्या का विस्तार से वर्णन करें...',
    public_phone_optional: 'फोन (वैकल्पिक)',
    public_submitting: 'जमा हो रहा है...',
    public_submit: 'जमा करें',
    public_submitted_success: 'आपकी शिकायत जमा हो गई है और एआई द्वारा प्रक्रिया की जाएगी।',
    public_loading_ward: 'वार्ड डेटा लोड हो रहा है...',
    public_ward_scorecard: 'वार्ड स्कोरकार्ड',
    public_total_complaints: 'कुल शिकायतें',
    public_resolved: 'समाधान हुआ',
    public_pending: 'लंबित',
    public_avg_resolution: 'औसत समाधान',
    public_hours: 'घंटे',
    public_trust_score: 'ट्रस्ट स्कोर',
    public_responsiveness: 'प्रतिक्रियाशीलता',
    public_resolution: 'समाधान दर',
    public_transparency: 'पारदर्शिता',
    public_citizen_satisfaction: 'नागरिक संतुष्टि',
    public_recent_actions: 'हाल की कार्रवाइयां',
    public_no_recent_actions: 'इस वार्ड के लिए कोई हाल की कार्रवाई नहीं',
    public_recently_updated: 'हाल ही में अपडेट',
    public_ward_map: 'वार्ड मानचित्र',
    public_footer: 'पारदर्शी स्थानीय शासन को सशक्त बनाना',
    public_submission_failed: 'जमा विफल',

    my_title: 'मेरी शिकायतें',
    my_subtitle: 'पूरी शिकायत हिस्ट्री और नवीनतम प्रगति टाइमलाइन ट्रैक करें।',
    my_total: 'कुल',
    my_open: 'खुली',
    my_in_progress: 'प्रगति पर',
    my_resolved: 'समाधान',
    my_add_mobile_hint: 'शिकायत इतिहास देखने के लिए My Profile में मोबाइल नंबर जोड़ें।',
    my_search: 'खोज',
    my_search_placeholder: 'शिकायत टेक्स्ट खोजें',
    my_status: 'स्थिति',
    my_all_statuses: 'सभी स्थितियां',
    my_refresh: 'रीफ्रेश',
    my_latest_notifications: 'नवीनतम सूचनाएं',
    my_notifications_subtitle: 'आपकी शिकायतों के लिए लीडर प्रतिक्रिया और स्थिति बदलाव।',
    my_recent: 'हाल की',
    my_loading_notifications: 'सूचनाएं लोड हो रही हैं...',
    my_no_notifications: 'अभी कोई सूचना नहीं। लीडर स्थिति बदलेंगे तो अपडेट दिखेगा।',
    my_complaint_update: 'शिकायत अपडेट',
    my_open_complaint: 'शिकायत खोलें',
    my_loading_complaints: 'शिकायतें लोड हो रही हैं...',
    my_no_filtered: 'चुने गए फ़िल्टर के लिए कोई शिकायत नहीं मिली।',
    my_complaint: 'शिकायत',
    my_view_details: 'विवरण देखें',
    my_latest_feedback: 'नवीनतम लीडर प्रतिक्रिया',
    my_no_leader_note: 'अभी लीडर नोट नहीं है। स्थिति बदलने पर सूचना मिलेगी।',
    my_progress_timeline: 'प्रगति टाइमलाइन',

    help_title: 'मदद चाहिए?',
    help_subtitle: 'तुरंत सहायता के लिए जनसेवा हेल्पलाइन पर कॉल करें',
    help_call_now: 'कॉल करें 1800-123-456',
    help_center_tag: 'सपोर्ट हब',
    help_center_title: 'जनसेवा हेल्प सेंटर',
    help_center_subtitle: 'नागरिकों, लीडर्स, अधिकारियों और इंजीनियरों के लिए भूमिका-आधारित मार्गदर्शन। जनसेवा की आंतरिक नॉलेज बेस से संचालित।',
    help_center_search_placeholder: 'खोजें: असाइनमेंट, वेरिफिकेशन, नोटिफिकेशन, ट्रैकिंग...',
    help_center_search: 'सहायता खोजें',
    help_center_reset: 'रीसेट',
    help_center_all_topics: 'सभी विषय',
    help_center_channel_phone: 'हेल्पलाइन',
    help_center_channel_phone_desc: 'गंभीर नागरिक समस्याओं के लिए तुरंत सहायता',
    help_center_channel_email: 'सपोर्ट ईमेल',
    help_center_channel_email_desc: 'ऑपरेशनल, ऑनबोर्डिंग और फीचर मार्गदर्शन',
    help_center_channel_sla: 'सामान्य SLA',
    help_center_channel_sla_desc: 'समस्या की गंभीरता और विभागीय भार पर निर्भर',
    help_center_guides: 'गाइड्स और SOPs',
    help_center_results: 'परिणाम',
    help_center_loading: 'हेल्प गाइड्स लोड हो रही हैं...',
    help_center_no_results: 'कोई मिलती-जुलती गाइड नहीं मिली। व्यापक कीवर्ड से खोजें।',
    help_load_failed: 'अभी हेल्प सेंटर लोड नहीं हो सका।',

    citizen_dash_header_tag: 'नागरिक विश्लेषण',
    citizen_dash_title: 'नागरिक रियल-टाइम डैशबोर्ड',
    citizen_dash_subtitle: 'आपकी शिकायतों, प्रतिक्रिया गति और नवीनतम लीडर अपडेट का लाइव ट्रैक।',
    citizen_dash_last_updated: 'अंतिम अपडेट',
    citizen_dash_load_failed: 'अभी आपका डैशबोर्ड विश्लेषण लोड नहीं हो सका।',
    citizen_dash_total: 'कुल',
    citizen_dash_active: 'सक्रिय',
    citizen_dash_resolved: 'समाधान',
    citizen_dash_critical: 'गंभीर',
    citizen_dash_recent7: 'पिछले 7 दिन',
    citizen_dash_rate: 'समाधान %',
    citizen_dash_recent_complaints: 'हाल की शिकायतें',
    citizen_dash_loading: 'लाइव विश्लेषण लोड हो रहा है...',
    citizen_dash_no_complaints: 'अभी कोई शिकायत नहीं। शुरुआत करने के लिए नई शिकायत दर्ज करें।',
    citizen_dash_live_updates: 'लाइव अपडेट',
    citizen_dash_no_updates: 'अभी कोई अपडेट नहीं। स्थिति बदलाव यहां दिखेंगे।',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('jansewa_lang') || 'en');

  const value = useMemo(() => ({
    language,
    setLanguage: (next) => {
      const normalized = next === 'hi' ? 'hi' : 'en';
      localStorage.setItem('jansewa_lang', normalized);
      setLanguage(normalized);
    },
    t: (key, fallback = '') => TRANSLATIONS[language]?.[key] || fallback || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
